### ISSUE TITLE
it wont work hoho

### ISSUE THREAD

**Issue by khaaayt** [quelbs/cyclotron#12]
![screenshot 2018-05-17 12 00 24](https://user-images.githubusercontent.com/31025989/40156066-110ff49c-594c-11e8-9d71-4e24f931e256.png)
![Uploading Screenshot 2018-05-17 12.00.32.png…]()
![Uploading Screenshot 2018-05-17 12.00.38.png…]()
![Uploading Screenshot 2018-05-17 12.00.43.png…]()

**Comment by mtelgkamp** [comment]
cyclotron is not standalone, it requires jQuery being loaded, also jquery.cyclotron.js and jquery.cyclotron.min.js are the same, so only one should be included. That is all I can see from the first screenshot, the other screenshots did not upload, so I cannot git further information.

**Comment by quelbs** [comment]
cyclotron is not standalone, it requires jQuery being loaded, also jquery.cyclotron.js and jquery.cyclotron.min.js are the same, so only one should be included. That is all I can see from the first screenshot, the other screenshots did not upload, so I cannot git further information.

**Comment by khaaayt** [comment]
i'll try uploading the other photos again

**Comment by khaaayt** [comment]
![screenshot 2018-05-17 12 00 32](https://user-images.githubusercontent.com/31025989/40184375-f146adf0-59a4-11e8-8046-20e12fc5154b.png)
![screenshot 2018-05-17 12 00 38](https://user-images.githubusercontent.com/31025989/40184376-f1f1546c-59a4-11e8-8eb1-909f90e67161.png)
![screenshot 2018-05-17 12 00 43](https://user-images.githubusercontent.com/31025989/40184377-f28c57be-59a4-11e8-87eb-6f9f15dec664.png)

**Comment by khaaayt** [comment]
have i done it correctly? hohoho i really need some help, thanks in advance

**Comment by khaaayt** [comment]
![screenshot 2018-05-17 12 00 32](https://user-images.githubusercontent.com/31025989/40189706-ee3450ce-59b1-11e8-8f2b-04d600fe4033.png)

**Comment by quelbs** [comment]
Please have a look at the [readme.md](https://github.com/quelbs/cyclotron/blob/master/readme.md). There it says the image has to be a css background image. Your option using an image inside a div does not work. You can also have a look at the [demo page](https://quelbs.github.io/cyclotron/) where you see more working examples.
