### ISSUE TITLE
Autorotation but nonContinuous?

### ISSUE THREAD

**Issue by dragoeco** [quelbs/cyclotron#5]
Hi, 

Not really and issue but a request: Is it possible to enable auto-rotaion but not endless? When I try autorotation:1 and continuous:0 (or nonContinuous class) together, the panorama stops sliding. I use a 180° picture and so I'd like the panorama stops where the image ends and then scroll to oposite side. Is this possible? Thanks

**Comment by quelbs** [comment]
I do not think it is possible right now, but it would be an enhancement. If autorotation:1 and continuous:0 are active the direction should be reversed at the edge of the image.
