### ISSUE TITLE
Not autoplay

### ISSUE THREAD

**Issue by smartwebcanada** [quelbs/cyclotron#6]
Hello,
I use your plugin for my wordpress site, but its not autoplaying. How can I make it autoplay?

Please advice.

**Comment by quelbs** [comment]
Do you use the parameters I use on the demo page?
.cyclotron({dampingFactor:1,autorotation:1});

**Comment by smartwebcanada** [comment]
Hello,
Yes.. I did use that..
Here is what I used..
<script type="text/javascript">
 jQuery(document).ready(function() {
jQuery('.auto360').cyclotron({dampingFactor:1,autorotation:1});
});
</script>

**Comment by leon9208** [comment]
Hi, great plugin, but how to make that picture povysote filled. I decided to do without repetition, in the styles have background-size: cover, but the view is repeated in a circle, and an empty space on the right ... here is an example:
http://codepen.io/leon9208/pen/ZBpEKd?editors=1010

**Comment by quelbs** [comment]
As it works for me, I would need to see the page where it does not work to find the problem.

**Comment by smartwebcanada** [comment]
Hello,
Here is the page link..
http://www.focusonsmiles.ca/wp3/

Thank you

**Comment by quelbs** [comment]
The version of cyclotron on this page is not the one from my branch, but the one from the original branch of mahonnaise/cyclotron. The original does not support autorotation. Please use the script from my branch https://raw.githubusercontent.com/quelbs/cyclotron/master/jquery.cyclotron.min.js instead.

**Comment by smartwebcanada** [comment]
Hello,
Thanks.. Added that code but it didnt worked out.. See site again.. Its not rotating :(
http://www.focusonsmiles.ca/wp3/

**Comment by quelbs** [comment]
Somehow there seems to be a conflict with another script loaded on the page. If I call the function in the console after the whole page is loaded, the autorotation works.

**Comment by smartwebcanada** [comment]
Thanks.. Got this error I found on the firebug console..
TypeError: $ is not a function, is there away we can changed your min.js file to be compatible?

**Comment by quelbs** [comment]
I did some changes in 55c19f04ffcffefe9c784e9a497aad99b69bbfe1 please try the most recent version of the script.

**Comment by smartwebcanada** [comment]
Thanks. 
I changed it.. But now it gives me this error on the console..
ReferenceError: checkOffset is not defined at line 136.

**Comment by quelbs** [comment]
I will follow up this in #8

**Comment by smartwebcanada** [comment]
Works now!!! Thank you!!!!!!
