### ISSUE TITLE
Allow images to be resized by "background-size"

### ISSUE THREAD

**Issue by leon9208** [quelbs/cyclotron#7]
Hi, great plugin, but how to make that picture povysote filled. I decided to do without repetition, in the styles have background-size: cover, but the view is repeated in a circle, and an empty space on the right ... here is an example:
http://codepen.io/leon9208/pen/ZBpEKd?editors=1010

**Comment by quelbs** [comment]
Cyclotron does not respect the CSS property "background-size" it still uses the original image width. Currently the original image is not allowed to be resized by CSS for Cyclotron to work correctly.

**Comment by leon9208** [comment]
Is there another way to pan the image to fill the height without using CSS ? Sorry fo my English ...

**Comment by leon9208** [comment]
Cool, now with the property background-size: cover; No right white strip (empty space), but if I choose a non-continuous mode, the panorama turns around, can I do something wrong?
Example: http://codepen.io/leon9208/pen/ZBpEKd?editors=1010

**Comment by quelbs** [comment]
If you use a 360° panorama (continuous:1) together with damping:1 and  autorotation:1 the image always moves in one direction. For non-continuous images the direction changes at the image border. If you want it to continue in the same direction you should not set continuous to 0.

**Comment by leon9208** [comment]
`<div class="pano1" style="background:url(/img.jpg);background-size: cover;height:400px;"></div>`

`	$(document).ready(function() {
		$('.pano1').cyclotron({continuous:0});
	});`
With these parameters, the panorama does not revolve around, but should from the border to the border of the image, as you have shown in the demo site. But I prokruichaetsya in a circle with the mouse.

**Comment by quelbs** [comment]
I did some changes in 55c19f04ffcffefe9c784e9a497aad99b69bbfe1 please try the most recent version of the script.

**Comment by leon9208** [comment]
`	$(document).ready(function() {
		$('').cyclotron(); //working
		$('').cyclotron({dampingFactor:1,autorotation:1}); //working
		$('').cyclotron({continuous:0}); //does not work
		$('').cyclotron({continuous:0,dampingFactor:1,autorotation:1}); //does not work
	});
`

**Comment by quelbs** [comment]
There seems to be a problem doing it with class names. When using id="pano1" instead of class="pano1" having continuous and non continuous panorama on one page works.
```
$(document).ready(function() {
	$('#pano1').cyclotron();
	$('#pano2').cyclotron({dampingFactor:1,autorotation:1});
	$('#pano3').cyclotron({continuous:0});
	$('#pano4').cyclotron({continuous:0,dampingFactor:1,autorotation:1});
});
```

**Comment by leon9208** [comment]
Nothing has changed. The last two variants are scrolled in a circle ... (((
I noticed that does not always work, sometimes have to refresh the page so that worked as it should. What could be the reason why so?

**Comment by quelbs** [comment]
Do you also have this problem on the main demo page?
For me the demo http://codepen.io/anon/pen/YpJJzP?editors=1010 always works fine in Firefox, in Chrome it only works if the image is in Cache on page load (e.g. on the second load of the page). So it seems to be another race condition only affecting Chrome? It may also be part of the problem that the image is loaded from a non-https URL on a https page. If you have any Idea how to fix this problem feel free to create a pull request (or a new issue).

**Comment by leon9208** [comment]
Yes, the problem is a demo page you are attached.
In such browsers like: Edge, Firefox, Opera is working properly, the problem in Internet Explorer 11, and Google Chrome.
The problem when you first load the site, you must refresh the page to work, you notice this problem is in Chrome and IE11

**Comment by quelbs** [comment]
Can you please open a new issue for this as I do not have time to have a
look on this right now.
